---

- include: package-apt.yml
  when: ansible_pkg_mgr == 'apt'

- include: package-yum.yml
  when: ansible_pkg_mgr == 'yum'

- include: package-dnf.yml
  when: ansible_pkg_mgr == 'dnf'

- include: package-brew.yml
  when: ansible_os_family == 'Darwin'

- include: package-zypper.yml
  when: ansible_pkg_mgr == 'zypper'

- include: package-pacman.yml
  when: ansible_pkg_mgr == 'pacman'

- include: package-portage.yml
  when: ansible_pkg_mgr == 'portage'
