---

- name: Pacman
  pacman:
    name: "{{ item.pacman | default(item.name) }}"
    state: "{{ item.state | default(package_state) }}"
  with_flattened:
    - package_list
    - package_list_host
    - package_list_group
