---

- name: Brew
  become: no
  homebrew:
    name: "{{ item.brew | default(item.name) }}"
    state: "{{ package_state }}"
  with_flattened:
    - package_list
    - package_list_host
    - package_list_group

