---

- name: Zypper
  zypper:
    name: "{{ item.zypper | default(item.name) }}"
    state: "{{ item.state | default(package_state) }}"
    update_cache: "{{ package_update_cache }}"
  when: (item.zypper_ignore|default('no'))|string in 'False,false,No,no'
  with_items: "{{ packages }}"
