---

- name: Yum
  yum:
    name: "{{ item.yum | default(item.name) }}"
    state: "{{ item.state | default(package_state) }}"
    update_cache: "{{ package_update_cache }}"
  with_flattened:
    - package_list
    - package_list_host
    - package_list_group

