---

- name: Zypper
  zypper:
    name: "{{ item.zypper | default(item.name) }}"
    state: "{{ package_state }}"
  with_flattened:
    - package_list
    - package_list_host
    - package_list_group
