---

- name: dnf
  dnf:
    name: "{{ item.dnf | default(item.name) }}"
    state: "{{ item.state | default(package_state) }}"
    update_cache: "{{ package_update_cache }}"
  when: (item.dnf_ignore|default('no'))|string in 'False,false,No,no'
  with_items: "{{ packages }}"
