---

- name: Apk
  apk:
    name: "{{ item.apk | default(item.name) }}"
    state: "{{ item.state | default(package_state) }}"
    update_cache: "{{ package_update_cache }}"
  when: (item.apk_ignore|default('no'))|string in 'False,false,No,no'
  with_items: "{{ packages }}"