---

- name: Zypper
  zypper:
    name: "{{ item.zypper | default(item.name) }}"
    state: "{{ item.state | default(package_state) }}"
  when: (item.zypper_ignore|default('no'))|string in 'False,false,No,no'
  with_items: "{{ (package_list + package_list_group + package_list_host ) | list | unique }}"
